server:
  port: 8088

logging.file: logs/application.log
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR


spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:h2db
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2

  flyway:
    enabled: true
    table: schema_version